### ISSUE TITLE
Add eighth note option

### ISSUE THREAD

**Issue by don-philipe** [thetwom/toc2#22]
Hi,

an option to add eighth notes/rests would be very nice. Then rhythmic patterns like clave would be easier to insert as with only quarter notes.

Btw. I like that app very much :smiley:

**Comment by thetwom** [comment]
Hi,
thanks for your suggestion. Up to now, I am hesitant to implement such a feature since it would be quite some work to implement it in a nice way (it must be intuitive to select the note duration, ideally two eighth notes would connect with a bar if they are next to each other, the user would need a way to tell if the selected speed belongs to quarters or to eighth notes). 
Still, I agree that it would be a nice option to have. At the moment I don't have enough time to implement it, but I will keep the issue open. Maybe I will find time some day ...

**Comment by bb010g** [comment]
+1 for setting note durations; they feel like they haven't arrived yet to the current UI. I don't think properly typesetting tied notes should be a priority; currently repeated quarter rests are not typeset as half or full rests.

I think a note duration slider would fit in, with discrete divisions for note lengths? For example:

```
[             delete             ]
 [ 1/16|1/8 (1/4 )1/3 |1/2 |1/1 ]
  [  base  ][ snare  ][ sticks ]
  [ wodblk ][ claves ][ hihat  ]
  [  mute  ]
[                        (volume)]
[              done              ]
```

Here, separators are be shown between note durations, and the separators immediately to the left & right of a note are obscured by the volume-slider style selection shape to maintain compactness while still clearly noting which duration is selected.

Note durations here are stolen from the [DB-66 metronome](https://www.boss.info/us/products/db-66/), which had volume sliders for (label - semantics):
1. quarter - (1/4) * 4
2. eighth rest, eighth - ({1/8}, 1/8) * 4
3. sixteenth rest, sixteenth, sixteenth rest, sixteenth - ({1/16}, 1/16, {1/16}, 1/16) * 4
4. triplet - (1/3, 1/3, 1/3) * 1

These have been extended to include half & whole notes because our software UI allows space for them. If there's space, dotted quarter (3/16) would probably be a good addition too?

Animation-wise, I think the slider shouldn't discontinuously jump, but should ease between settings with some [easeInOutExpo] or [easeInOutCirc], and when released should "snap" back to the setting's center (thanks to the easing function in presentation, a simple linear ease on the backing value should be fine). Additionally, notes in the picker & the selected note should smoothly transform between different durations (sixteenth, eighth, quarter, third, dotted quarter(?), half, whole), synchronized with the slider's easing between duration settings.

[easeInOutExpo]: https://easings.net/#easeInOutExpo
[easeInOutCirc]: https://easings.net/#easeInOutCirc

**Comment by thetwom** [comment]
Thanks for your interest and for your suggestions! 

I guess you are right that it is not really needed to tie notes together. That would at least significantly ease the implementation. 

My feeling is that a slider would not be perfectly appropriate, but we should rather have a row of buttons next to each other, where each button shows a duration choice. This would allow the user to directly select the duration he wants without having to "search" the duration by sliding. Buttons next to each other of course need more space, which would restrict the number of choices. 

My feeling would be, that half and whole notes are not that important (can be faked with rest notes) and indeed the visualization is not easy for all note types. Also dotted notes can be fakes with rests, so these would also be not be of major importance. So we could have 1/16, 1/8, 1/4. Then maybe triplets (triplet over three eights, triplet over three quarters), and not sure about quintuplets (e.g. quintuplet over 5 eights). These would be already six choices, which I think is a the maximum for the gui to not become too cluttered. 

Unfortunately, 1/8 and 1/16 notes need more horizontal space, so with many notes, they would be partly be cut ...

And there still remains the question how to nicely visualize the tuplet notes without tying ...

In total, it should be doable, but I don't know when I find time to implement this since it will be quite some work ... 

In the meantime, we can use this thread for collecting opinions and ideas ...

**Comment by bb010g** [comment]
The slider would effectively be a row of buttons, but I think having it feel like a slider over discrete modes would be a better fit for the application. I would expect the slider to jump directly to any note duration that was directly tapped on.

What's the minimum screen density & resolution combo we're aiming to support?

**Comment by thetwom** [comment]
The minimum resolution I test with is 240x432 with ldpi density.

**Comment by thetwom** [comment]
I have published a beta version where you can test different note durations: [v4.0.0-beta1](https://github.com/thetwom/toc2/releases/tag/v4.0.0-beta1). Maybe you are willing to test, but WARNING: the format changed how scenes are saved, meaning that you can NOT GO BACK to older versions and at the same time keep the scenes.

**Comment by don-philipe** [comment]
Cool, I will have a look at it today and test it.

**Comment by don-philipe** [comment]
I've tested that new feature in the beta version and I really like it. Haven't found any issues by now.

**Comment by thetwom** [comment]
Thanks for testing, will take some time, until I release it. Too many chances to simply do it :-)

**Comment by thetwom** [comment]
Closing this as it is now available in v.4.0.0.
