### ISSUE TITLE
Add option to disable sound

### ISSUE THREAD

**Issue by Porrumentzio** [thetwom/toc2#23]
So only vibration can be used

**Comment by thetwom** [comment]
Thanks for your suggestion. Up to now I didn't add such an option since it can easily be accomplished by turning down the volume. But it's the second request for this option. If you give a good reason why turning down the volume is no option, I might reconsider :-)

**Comment by Porrumentzio** [comment]
I didn't think about turning down the volume, I thought it more from a energy saving view (I don't know if playing muted sound spends battery)

I don't manage to think of a situation in which audio should be played from device, but metronome beats no.

I first thought that the option of using metronome only as vibrantion was not contemplated by design, because there's no any reference to it.


I'll open another issue about thoughts about vibration!

**Comment by thetwom** [comment]
Regarding energy saving, it won't help. Let me quickly explain:
The first versions app just used a "delay" function to establish the ticking. However, the quality was insufficient for several people (#3) since this was a thread-based mechanism and there is no guarantee by Android, that the thread wakes up in time. So I came up with something better, mixing directly an audio stream, which is played as a continuous audio track. This mechanism works very well and allows callbacks, such that at given time stamps we can call vibration or trigger graphical effects. In other works, in order to get the metronome ticking we must play the audio stream.

So, if I understand you correctly, a "mute"-button would be of no real benefit. But let's keep this issue open and see if more such requests come in ...

**Comment by babloyi** [comment]
Consider this a third request for this feature! I'd like to be able to use the metronome purely based on the vibration, and with no sound. Currently muting my phone, but it would be nice if the in-app volume control handled this.

**Comment by thetwom** [comment]
Thanks for letting me know, I will give it more thought, when I find some time. Might take a while though.

**Comment by thetwom** [comment]
A mute button is now available and ready to test: [v4.0.0-beta2](https://github.com/thetwom/toc2/releases/tag/v4.0.0-beta2)
WARNING: Starting with version 4.0.0 some internals changed for saving the settings and scenes! This means that you can not go back to an older version and keep your scenes.

**Comment by babloyi** [comment]
Vibration mode appears to be working perfectly!

**Comment by thetwom** [comment]
Closing this as available in v4.0.0
