### ISSUE TITLE
Add ability to define tempo by keyboard input

### ISSUE THREAD

**Issue by Porrumentzio** [thetwom/toc2#26]
Touching or long pressing the green BPM number at the top of screen should able to define the BPM by keyboard input (same as for maximum/minimum speed at settings)

**Comment by thetwom** [comment]
I was thinking about the need for this input method before, but didn't implement it since I realized that typing a speed would always be slower than just swiping along the speed-changing circle. 

Maybe you can let me know the scenario when typing a specific speed would make sense. In this way we could think of it makes sense to allow typing the number of if there is even a more suitable way to select the speed ...

**Comment by Porrumentzio** [comment]
Well, for me is not speeder swiping! If I know that a song has 220 tempo, it's much more easier and rapid to input by keyboard, than swiping (think you start from 160, there are 60 bpms to move)

I would really like the input method, as it does not change the UI and is more comfortable for me :)

**Comment by thetwom** [comment]
Thanks for the answer. I will keep this in mind and when I find time implementing it in a nice way.

**Comment by thetwom** [comment]
Please checkout the following beta for a selectable speed text: [v2.5.0-beta1](https://github.com/thetwom/toc2/releases/tag/v2.5.0-beta1).
I attached there a apk for manual installation. Also consider updating the basque (and maybe other) translations ...

**Comment by Porrumentzio** [comment]
Great! I'll update that string. The default now is in deustch or something similar

**Comment by thetwom** [comment]
Sorry, the default should be English, but I accidently inserted the German translations to the Basque file ...
