### ISSUE TITLE
Light-pulse metronome

### ISSUE THREAD

**Issue by Long-FA** [thetwom/toc2#28]
Sound-based metronome is widely used, but it has some drawbacks. Since metronome sound is repetitive and annoying, listening to it for a while with allow our brain to catch the pattern and create anti-click sound as an attempt to suppress the metronome. That's why if you turn on the metronome, listen to it continously for a few minutes while focusing on your musical piece, at some point you will feel like you can't hear the metronome anymore. 
Light-pulse metronome is invented to address this issue. By using a red light running up and down, our brain can't find a way to supress this. Light pulse also doesn't get mixed up with the music you are playing, unlike sound-based metronome.

An example of a light-pulse metronome: https://youtu.be/0RBOakMAqws?list=PL8hZtgRyL9WRWJLlIUPl-ydiDc8CZ_SJK&t=267

I noticed that your metronome already has a green bar running at the bottom of the screen, so in order to create something that resembles a light-pulse metronome, you only have to:

- Rotate the green bar to vertical and increase its size to cover the entire phone's height.
- Eliminate the fading effect.
- Make sure the green bar is running at constant speed (that is, no acceleration the further green bar is from center).
- And maybe add some 8th note, 16th note marks (you know, like those in a thermometer).

**Comment by thetwom** [comment]
Thanks a lot for your interesting thoughts. It is indeed an open question of how to best visualize the clicks. Yet I am not sure, how your suggestions would improve the feeling:
- Why is it important to have a vertical bar instead of a horizontal one? Since it would be longer? While this might help for low speeds, it would not look good for high speeds. That's why the moving range of the green marker is shortened with increasing speeds.
- We could argue about the fading effect, but at the moment it is used to have a more pronounced "click" effect. But I currently can't say if it really does the trick :-)
- Constant speed or acceleration is also a good question. In my experience, a constant speed makes it much harder to predict, when the click really occurs. I think, accelerated motions are much more natural. Think of a bouncing ball. You intuitively can predict, when it will hit the ground by a quite high accuracy. This underlies accelerated motion. If you use constant motion, I think that you loose a lot of accuracy.

But even though there is already quite some though of why the green bar animation is as it is, I don't claim it to be ideal. Please let me know about your further thoughts and maybe we can find a way to improve it.

**Comment by Long-FA** [comment]
>     * Why is it important to have a vertical bar instead of a horizontal one? Since it would be longer? While this might help for low speeds, it would not look good for high speeds. That's why the moving range of the green marker is shortened with increasing speeds.

Making it vertical and bigger will allow us to see the metronome from a distance, that's all. When playing music we can't hold the phone 30 centimeters in front of our faces.
 
>     * Constant speed or acceleration is also a good question. In my experience, a constant speed makes it much harder to predict, when the click really occurs. I think, accelerated motions are much more natural. Think of a bouncing ball. You intuitively can predict, when it will hit the ground by a quite high accuracy. This underlies accelerated motion. If you use constant motion, I think that you loose a lot of accuracy.
> 
Without constant speed, the green bar won't hit 8th note and 16th note accurately.

**Comment by thetwom** [comment]
Thanks for your further comments. From your latest comments I find two requests:
1. Having a more prominent click indicator, such that one can easily "read" it from some distance.
2. Being able to 8th, or even 16th note clicks.

Regarding request 1: I think making it vertical won't help too much. But we could think of making it more prominent. Maybe we could also find a better animation, which feels more natural. However, it is important that the animation works well for low and high speeds. This brings me to
Request 2: In one of the first versions of the app, I had a kind of progress bar below the notes, which progressed with constant speed, also showing at which note we currently are. So this was a bit similar to your request. However, while using it I realized it is of almost no help. With a constant speed you have to concentrate very hardly on the bar to "feel" the click. If speed increases this will become even harder. Meaning that if you use marks at 8th or 16th note, only for very low speeds they might be of help. Together with a constant speed indicator this would mean that you have to concentrate on the metronome instead of on your music. 

1. We could think of better visual indication.
2. At the current state I would not think further into visualizing 8th or 16th. If a good idea pops up, I might reconsider :-). In the meantime, you could just double your speed and use quarter notes as 8th notes ...

**Comment by Long-FA** [comment]
It's true that reading 8th and 16th notes marks is impossible at high tempo which is why...no one do that. 8th and 16 note marks are only meant for slower music. But implementing 8th and 16 marks has to go with constant speed running bar because you wouldnt be able to hit 8th and 16th accurately otherwise. 
I thought vertical bar would be better because it can make use of the entire phone height. The bar should be big enough so you can read it from about 50 centimeters away, like when you place your phone on the music rest. I tried the currrent horizontal bar and it's too small to see from a distance.

**Comment by thetwom** [comment]
Thanks for your answer. 
I am regularly using my phone 50cm away and it works nicely.  So in order to understand your point, I would be interested in what phone you are using (or screen size + screen resolution). Alternatively, a screenshot. 

I will put some thought, if there is a better way for visualizing the ticks. As said, I don't favor a constant speed bar. But maybe we can up with something even better with accelerated motion, which indicates at least 8th notes ... . 

Unfortunately, my time is rare at the moment, so sorry, that there will be no short term solution for that.

**Comment by Long-FA** [comment]
I understand. Please reopen the issue when you have some free time or come up with a viable approach.
