### ISSUE TITLE
App crashes if tempo is 0 or very high

### ISSUE THREAD

**Issue by qwerty287** [thetwom/toc2#34]
Hi, 
the app crashes if the tempo is 0 BPM. I know, you don't use a metronome to set it to 0 BPM, but it just would be enough if the option in the setting doesn't accept a value of 0. It's the same if the value is very high. 
And if you set the value in the settings and the BPM to 1000 or more (in German), and then open the entry dialog by clicking on the BPM value and then just click OK - Metronome will think you mean 1 because it separates the numbers with a dot ("1.000"), which is interpreted as "1" (solution would be to remove the dot, for example - not a good solution - you could convert the number to an integer and then back to a string, this would solve it).

**Comment by thetwom** [comment]
Hi, 
thanks for testing the apps with non-typical values.  You are absolutely right, that we should not allow 0bpm or too high values. 
I pushed an update now with the following changes:
- Still allows setting a minimum value of 0bpm in the settings, but don't allow to set the actual speed to zero. 
- Set limit to the maximum value of 10000. (Maybe you can confirm, that such high values don't cause the app to crash for you). 
- Don't use the thousands grouping character in the dialog of setting a new speed.
Since your reported issues should don't appear to be very severe, I will wait for more changes (or at least some time) until tagging a new release.

Best regards and thanks again for reporting.
