### ISSUE TITLE
User interface broken

### ISSUE THREAD

**Issue by Heidistein** [thetwom/toc2#40]
Hi,
I enjoy the app for a long time now. However, recent there was an update, which breaks the user interface, the tempo-wheel overlays everything, see screenshot:
https://nextcloud.beetjevreemd.nl/index.php/s/Z4DqJo6NFZHRFbP

I am running the latest 4.0.1, from f-droid.

**Comment by thetwom** [comment]
Thanks for the report and sorry to hear. Can't open your figure due to security warnings in my browser. 

However, I had a similar report recently (#38) which led to version [v4.1.0](https://github.com/thetwom/toc2/releases/tag/v4.1.0). Unfortunately, fdroid takes quite some time to  pick it up. So can you either try the apk directly and report if this fixes the problem for you? Alternatively, you can wait for fdroid ... . Please let me know if the problem exists further ...

**Comment by spaetz** [comment]
Hi fdroid is on 4.1.2 now and at least on kine, the screen looks nice. Just for the record I downloaded the screenshot of @Heidistein and will attach it here.
![Screenshot_20210910-080341](https://user-images.githubusercontent.com/63132/132807478-31d49a9e-3d9b-4142-807c-89be45bb8f41.png)

**Comment by thetwom** [comment]
Thanks for  attaching the figure. This should indeed be the same problem as reported in #38. I am glad that it works fine now!

**Comment by Heidistein** [comment]
Oh, right. Yes, sorry for not replying. I tried compiling the app myself and got stranded somewhere. Next f-droid finished their build, which, indeed, fixed the problem.
