### ISSUE TITLE
Remove lower cap on bpm

### ISSUE THREAD

**Issue by BitPuffin** [thetwom/toc2#63]
Hello! Thank you so much for this app, I use it a lot and I love it.

However I have found that the 20bpm lower limit gets in the way sometimes. Not because I play at 15bpm but it's a useful exercise to set the metronome really low so that it only clicks on some of the beats while you are responsible for more of them. (As is shown in this video: https://youtu.be/u6hg8GcLc-4 ). So I would love it if the limit was either removed or if there was a setting to turn it off. Thanks!

**Comment by thetwom** [comment]
Glad you like the metronome. 

Actually, there is already an option (Minimum speed), which allows you to change the minimum speed.

The standard minimum is at 20bpm, since very small speeds can degrade the user experience a bit. E.g. when you accidentally go down to 1bpm, and afterwards go up again, while having the metronome playing, you must wait up to a minute until the last 1bpm-beat finishes and you experience the faster speed again. 

If you purely rely on audible feedback, there is actually an other option, which I personally prefer. I am just adding several "pause"-notes. Then I can use the original speed, but hear only a beat e.g. each bar or less ...

Let me know if this solves your issue.

**Comment by BitPuffin** [comment]
Oh wow yeah! That's great that I can already do it. Not sure how I managed to miss it when looking in the settings. Also the idea of adding rests is very good!

**Comment by thetwom** [comment]
>  Not sure how I managed to miss it when looking in the settings.

Maybe there are too many settings ;-). Glad to have solved an issue so easily :-).
