### ISSUE TITLE
Feature Request: Please allow the ability to remove individual rhythm presets ("scenes") instead of the entire list

### ISSUE THREAD

**Issue by Zeitiah** [thetwom/toc2#64]
It's kinda annoying that in order to remove one, I'd have to delete all of them.

**Comment by thetwom** [comment]
Hi, it seems that deleting scenes is more hidden, than I would expect, since you are not the first one, asking this. You can simply delete single scenes by swiping it to the left. Maybe I have to find a way some time, to make this more obvious ...

Let me know, if this answer at least answers the question for you.

**Comment by Zeitiah** [comment]
Lol, thank you for replying to my issue. I really appreciate how you are so active on here. I love the metronome and tuner apps, thanks.
